name: "SolarSynkV3a"
description: "Home Assistant add-on for syncing solar/inverter data from SynSynk.net"
version: "1.1"
slug: "solar_synkv3a"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/Jess--/solarsynk_test/tree/main"
  
  
options:
  sunsynk_user: ""
  sunsynk_pass: ""
  sunsynk_serial: ""
  Home_Assistant_IP: ""
  Home_Assistant_PORT: 8123
  HA_LongLiveToken: ""
  Refresh_rate: 300
  Enable_HTTPS: false
  API_Server: "api.sunsynk.net"  
  
schema:
  sunsynk_user: str
  sunsynk_pass: password
  sunsynk_serial: str
  Home_Assistant_IP: str
  Home_Assistant_PORT: int
  HA_LongLiveToken: password
  Refresh_rate: int
  Enable_HTTPS: bool
  API_Server: list(api.sunsynk.net|pv.inteless.com)





